# Generated by Django 5.2.3 on 2025-07-02 05:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_messageboard', '0002_messageboard_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messageboard',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_messageboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='messageboard',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_messageboards', to=settings.AUTH_USER_MODEL),
        ),
    ]
